version: '{build}'

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /\[ci skip\]/

image: Visual Studio 2019 Preview

init:
  - git config --global core.autocrlf input

platform: x64

configuration: Release

before_build:
  - nuget restore .\src\WinQuickLook\WinQuickLook.csproj

build:
  project: .\src\WinQuickLook\WinQuickLook.csproj
  verbosity: minimal