version: 1.1.{build}

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /\[ci skip\]/

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"

platform: Any CPU

configuration: Release

build:
  verbosity: minimal

artifacts:
  - path: src\WinQuickLook\bin\$(configuration)
    name: WinQuickLook