//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinQuickLook.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinQuickLook.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Launch on Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoStartText {
            get {
                return ResourceManager.GetString("AutoStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applications cannot be launched because Desktop Composition (DWM) is disabled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DwmDisabledErrorMessage {
            get {
                return ResourceManager.GetString("DwmDisabledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileItemCount {
            get {
                return ResourceManager.GetString("FileItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileTypeDirectory {
            get {
                return ResourceManager.GetString("FileTypeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last modified {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastModifiedText {
            get {
                return ResourceManager.GetString("LastModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t open this file with associated program. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenButtonErrorMessage {
            get {
                return ResourceManager.GetString("OpenButtonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open with {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenButtonText {
            get {
                return ResourceManager.GetString("OpenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PageCountText {
            get {
                return ResourceManager.GetString("PageCountText", resourceCulture);
            }
        }
    }
}
